# Generated by Django 3.2.7 on 2021-09-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoomApp', '0002_auto_20210909_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='create_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='update_date',
            field=models.DateField(blank=True),
        ),
    ]
