# Generated by Django 3.2.7 on 2021-09-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoomApp', '0004_auto_20210909_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='update_date',
            field=models.DateField(null=True),
        ),
    ]
